site_name: FeOx
theme:
  name: material
  palette:
    scheme: slate
    primary: deep orange
    accent: orange
nav:
  - Home: index.md
  - Getting Started: getting-started.md
markdown_extensions:
  - admonition
  - pymdownx.details